### ISSUE TITLE
Links don't work on footer.

### ISSUE THREAD

**Issue by gopalmani** [ayushsgithub/Cryptobase#1]
![image](https://github.com/ayushsgithub/Cryptobase/assets/45264570/a4912a3d-de82-4642-bfd6-0b5590875b89)

**Comment by ayushsgithub** [comment]
> ![image](https://user-images.githubusercontent.com/45264570/266102765-a4912a3d-de82-4642-bfd6-0b5590875b89.png)

Hey @gopalmani buddy, it's great to see you here.
I'm sorry about the links, but this project is built only for learning purpose and it has some issues, whenever I get on this project again, I will make sure most of the things work.
Thank you.
